<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5grrj8q\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5grrj8q/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5grrj8q.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5grrj8q\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5grrj8q\appProdProjectContainer(array(
    'container.build_hash' => '5grrj8q',
    'container.build_id' => '22784ca0',
    'container.build_time' => 1567763489,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5grrj8q');
